### ISSUE TITLE
Module remove `-` before `server` on Windows

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadminio-io_weblogic#10]
In the `setEnv.cmd` file, the first option for `JAVA_OPTIONS_WIN` is `-server`. When the module runs the `ini_subsetting` type removes the `-`.

It should be 
```SET JAVA_OPTIONS_WIN=-server -Xms256m``` 
but we get 
```SET JAVA_OPTIONS_WIN=server -Xms256m```

This prevents WebLogic from starting on Windows.

**Comment by iversond** [comment]
One solution (tested on Windows), is the remove the class default `subsetting_separator => '-'` and add the `-` to the Hiera data structures.

```
io_weblogic::java_options:
  "%{hiera('db_name')}":
    -Xms:                              '256m'
    -Xmx:                              '256m'
```

**Comment by ericbisme** [comment]
Merged Dan's fix for above and tested on Linux with revised hiera. Updated README example to reflect hiera change.
